### ISSUE TITLE
Update the Geotools reference

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/geographtools#2]
It appears that the current Geotools dependecy does not work with Java 9. It should be updated and tested together with Amodsim and demo packages. Then, new minor versions of all related packages should be released.

**Comment by F-I-D-O** [comment]
How to solve it:
1. download and install the newest jdk https://www.oracle.com/technetwork/java/javase/downloads/index.html

1. try to build(mvn compile) geotools with the new jdk, update dependencies if needed

1. try ap demo on the new jdk with updated dependencies

1. try ap demo on the old jdk (8) with updated dependencies

**Comment by matalukes** [comment]
Fixed on branch bug/reference

**Comment by F-I-D-O** [comment]
Fixed by updating geotools and releasing new versions of all packages.
